title: Müge Karagöz, PhD
logo: assets/img/Muge-Karagoz.jpg
description: 
description: 
  Committed and experienced researcher and educator with a history of working in large-scale research collaborations and world-leader institutions. 
  <br><br>
  Faculty Leader of the Simulating Particle Detection (SPD) research stream within the UMD FIRE undergraduate program where I have brought my expertise into my curriculum.
  I aim to instill in my students an appreciation of curiosity-based basic science through the lens of computational and data analysis methods applied on cutting-edge particle physics experiments.
  <br><br>
  <a href="https://www.linkedin.com/in/mugekaragoz/">View My LinkedIn Profile</a> 
#show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
